[project]
name = "unit-of-work"
version = "0.1.0"
description = "Simple implementation Unit of Work pattern (M.Flower)."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.3",
    "ruff>=0.6.9",
]
