CREATE TABLE IF NOT EXIST posts (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	title TEXT NOT NULL
);


CREATE TABLE IF NOT EXIST comments (
	id INTEGET PRIMARY KEY AUTOINCREMENT,
	body TEXT NOT NULL,
	post_id INTEGER NOT NULL,
	FOREIGN KEY (post_id) REFERENCES posts (id)
);
